### ISSUE TITLE
cart.go 142行

### ISSUE THREAD

**Issue by Godblessjovi** [harlanc/moshopserver#5]
原文是：		
`o.QueryTable(carttable).Update(orm.Params{"number": orm.ColValue(orm.ColAdd, intnumber)})`

我的理解似乎应该是：
`o.QueryTable(carttable).Filter("id", cart.Id).Update(orm.Params{"number": orm.ColValue(orm.ColAdd, intnumber)})`

**Comment by harlanc** [comment]
fixed ,thanks.
