### ISSUE TITLE
包依赖问题的疑问

### ISSUE THREAD

**Issue by caesar-empereur** [harlanc/moshopserver#7]
你的 models, utils 包都是在项目里面的，其他地方引入这些包的时候，都是这种
import (
	"encoding/json"
	"github.com/astaxie/beego/orm"
	"github.com/harlanc/moshopserver/models"
	"github.com/harlanc/moshopserver/utils"
)
这样引入的包是在本地缓存的，不是你工程里面的包， models 这些包里面的代码改动的时候也不会马上影响到其他引入的地方，这样不是很奇怪吗?

我试过这样引入包，也是可以的，而且代码改动的话可以马上影响到引入的地方
import (
	"encoding/json"
	"github.com/astaxie/beego/orm"
	"moshopserver/models"
	"moshopserver/utils"
)

个人认为第二种引入的方式才是比较合适的，是一个项目比价正常的依赖关系，有本地代码依赖和第三方的依赖，像 java 的 maven
一样。

而且 go mod 的依赖管理现在是比较成熟了，不用把代码放在 gopath 下面了

我是小白，如有得罪请见谅，只是提了一个疑问意见

**Comment by harlanc** [comment]
有个哥们提交了个PL也是你第二种方法，我有时间看一下哈

**Comment by harlanc** [comment]
有个pull request 解决了你说的这个问题，PR已经合并。

**Comment by harlanc** [comment]
你用的是什么IDE？
"github.com/harlanc/moshopserver/models"
"github.com/harlanc/moshopserver/utils"
这种引用方式我记得我在VS code上一个包的改动，是可以影响其他引入的地方的
